# Generated by Django 5.0.1 on 2024-01-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=223)),
                ('salary_offered', models.CharField(max_length=223)),
                ('job_type', models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'part-Time'), ('selling', 'Selling')], max_length=20)),
                ('age', models.IntegerField()),
                ('skills', models.TextField()),
            ],
        ),
    ]
