# Generated by Django 5.0.1 on 2024-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='education',
            field=models.CharField(default='DefaultEducationValue', max_length=255),
        ),
    ]
