# Generated by Django 5.0.1 on 2024-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmodule', '0002_jobdetails_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='education',
            field=models.CharField(max_length=255),
        ),
    ]
