# Generated by Django 5.0.1 on 2024-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmodule', '0003_alter_jobdetails_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='salary_offered',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='work_title',
            field=models.CharField(max_length=225),
        ),
    ]
